version: "3"


networks:
  backend:
    driver: ${NETWORKS_DRIVER}


volumes:
  redis:
    driver: ${VOLUMES_DRIVER}
  mariadb:
    driver: ${VOLUMES_DRIVER}
  mongo:
    driver: ${VOLUMES_DRIVER}
  owncloud:
    driver: ${VOLUMES_DRIVER}
services:


### Nginx ################################################

  nginx:
    build:
      context: ./services/nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        NGINX_INSTALL_APPS: ${NGINX_INSTALL_APPS}
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
      - "${NGINX_SSH_HOST_PORT}:22"
    volumes:
      - ${APP_CODE_PATH_HOST}:/www/:rw
      - ${NGINX_SSL_CERTIFICATE_DIR}:/ssl:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_SSH_DIR}:/etc/nginx/ssh/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_FASTCGI_PHP_CONF}:/etc/nginx/fastcgi-php.conf:ro
      - ${NGINX_FASTCGI_PARAMS}:/etc/nginx/fastcgi_params:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    environment:
      TZ: "$TZ"
    depends_on:
      - php
      - gogs
      - owncloud
    networks:
      - backend

### PHP ################################################

  php:
    build:
      context: ./services/php
      args:
        PHP_VERSION: php:${PHP_VERSION}-fpm-alpine
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        PHP_EXTENSIONS: ${PHP_EXTENSIONS}
        TZ: "$TZ"
    volumes:
      - ${APP_CODE_PATH_HOST}:/www/:rw
      - ${PHP_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP_LOG_DIR}:/var/log/php
      - ${DATA_PATH_HOST}/composer:/tmp/composer
    cap_add:
      - SYS_PTRACE
    networks:
      - backend

### MariaDB ##############################################

  mariadb:
    build:
      context: ./services/mariadb
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - MARIADB_VERSION=${MARIADB_VERSION}
    volumes:
      - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
      - ${MARIADB_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      - TZ=${TZ}
      - MYSQL_DATABASE=${MARIADB_OWNCLOUD_DATABASE}
      - MYSQL_USER=${MARIADB_OWNCLOUD_USERNAME}
      - MYSQL_PASSWORD=${MARIADB_OWNCLOUD_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    networks:
      - backend

### PostgreSQL ###########################################

#  postgres:
#    build:
#      context: ./services/postgres
#      args:
#        - POSTGRES_VERSION=${POSTGRES_VERSION}
#    volumes:
#      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
#      - ${POSTGRES_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
#    ports:
#      - "${POSTGRES_PORT}:5432"
#    environment:
#      - POSTGRES_DB=${POSTGRES_DB}
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - GITLAB_POSTGRES_INIT=${GITLAB_POSTGRES_INIT}
#      - GITLAB_POSTGRES_USER=${GITLAB_POSTGRES_USER}
#      - GITLAB_POSTGRES_PASSWORD=${GITLAB_POSTGRES_PASSWORD}
#      - GITLAB_POSTGRES_DB=${GITLAB_POSTGRES_DB}
#    networks:
#      - backend

### Redis ##############################################

  redis:
    build:
      context: ./services/redis
      args:
        REDIS_VERSION: ${REDIS_VERSION}
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
      - ${DATA_PATH_HOST}/redis:/data/:rw
    environment:
      TZ: "$TZ"
    networks:
      - backend

### Gitlab ################################################

#  gitlab:
#    build:
#      context: ./services/gitlab
#    environment:
#      GITLAB_OMNIBUS_CONFIG: |
#        external_url '${GITLAB_DOMAIN_NAME}'
#        nginx['listen_https'] = false
#        nginx['listen_port'] = 80
#        nginx['client_max_body_size'] = '1024m'
#        nginx['custom_gitlab_server_config'] = "set_real_ip_from 172.0.0.0/8;\nreal_ip_header X-Real-IP;\nreal_ip_recursive on;"
#        postgresql['enable'] = false
#        gitlab_rails['db_host'] = '${GITLAB_POSTGRES_HOST}'
#        gitlab_rails['db_username'] = '${GITLAB_POSTGRES_USER}'
#        gitlab_rails['db_password'] = '${GITLAB_POSTGRES_PASSWORD}'
#        gitlab_rails['db_database'] = '${GITLAB_POSTGRES_DB}'
#        redis['enable'] = false
#        gitlab_rails['trusted_proxies'] = ['caddy','nginx','apache2']
#        gitlab_rails['redis_host'] = 'redis'
#        gitlab_rails['redis_database'] = 8
#        gitlab_rails['time_zone'] = 'Asia/Shanghai'
#        gitlab_rails['smtp_enable'] = true
#        gitlab_rails['smtp_address'] = "smtp.qq.com"
#        gitlab_rails['smtp_port'] = 465
#        gitlab_rails['smtp_user_name'] = "ghostai@vip.qq.com"
#        gitlab_rails['smtp_password'] = "mlcwbcyqovftbfhf"
#        gitlab_rails['smtp_authentication'] = "login"
#        gitlab_rails['smtp_enable_starttls_auto'] = true
#        gitlab_rails['smtp_tls'] = true
#        gitlab_rails['gitlab_email_from'] = 'ghostai@vip.qq.com'
#    volumes:
#      - ${DATA_PATH_HOST}/gitlab/config:/etc/gitlab
#      - ${DATA_PATH_HOST}/gitlab/data:/var/opt/gitlab
#      - ${GITLAB_HOST_LOG_PATH}:/var/log/gitlab
#    networks:
#      - backend
#    depends_on:
#      - postgres
#      - redis
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "20m"
#        max-file: "10"

### Owncloud ################################################

  owncloud:
    build:
      context: ./services/owncloud
      args:
        OWNCLOUD_VERSION: ${OWNCLOUD_VERSION}
    volumes:
      - ${DATA_PATH_HOST}/owncloud/data:/mnt/data
    environment:
      - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=${MARIADB_OWNCLOUD_DATABASE}
      - OWNCLOUD_DB_USERNAME=${MARIADB_OWNCLOUD_USERNAME}
      - OWNCLOUD_DB_PASSWORD=${MARIADB_OWNCLOUD_PASSWORD}
      - OWNCLOUD_DB_HOST=mariadb
      - OWNCLOUD_ADMIN_USERNAME=${OWNCLOUD_ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${OWNCLOUD_ADMIN_PASSWORD}
      - OWNCLOUD_MYSQL_UTF8MB4=false
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    depends_on:
      - mariadb
      - redis
    networks:
      - backend




  ### Redis ##############################################

  gogs:
    build:
      context: ./services/gogs
    volumes:
      - ${DATA_PATH_HOST}/gogs:/data/:rw
    environment:
      TZ: "$TZ"
    networks:
      - backend

#  wordpress:
#    image: wordpress:latest
#    depends_on:
#      - mariadb
#    environment:
#      WORDPRESS_DB_HOST: mariadb:3306
#      WORDPRESS_DB_PASSWORD: root
#      WORDPRESS_DB_USER: root
#      WORDPRESS_DB_NAME: wordpress
#    networks:
#      - backend